CREATE TABLE IF NOT EXISTS contacts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Message TEXT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
);
